name: Run Streamlit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set executable permissions for chromedriver
      run: chmod +x chromedriver

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Streamlit app
      run: streamlit run app.py
