name: Run Streamlit App with Selenium

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    container: rileywallaceriley/bbblogger:latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run Streamlit App
      run: streamlit run BBBlogger.py
      # Use any necessary command to start your app/tests
